### ISSUE TITLE
Not find the 'disambiguation'module

### ISSUE THREAD

**Issue by zjulabwjt** [AIBluefisher/deep_bundle_adjusting_NeRF#1]
![image](https://user-images.githubusercontent.com/129039345/234854893-b5f70b79-61bb-4ec6-99a6-d924b6a281e5.png)
I follow the readme install envirment,but not find the 'disambiguation'module in the code.Now the opensourced code is lacked this module?Or the 'disambiguation' module is come from Hloc Project?Thanks for your help!

**Comment by AIBluefisher** [comment]
It is from [disambiguation-colmap](https://github.com/cvg/sfm-disambiguation-colmap.git). Sorry for missing this dependency. This module should be optional, however, the code is still under preparing and it is not fully tested. You can comment the related code or follow the installation instruction of disambiguating-colmap. We will fix this issue when we release our code.

**Comment by AIBluefisher** [comment]
It is fixed now. Refer to the [script](https://github.com/AIBluefisher/dbarf/blob/main/scripts/env/dependencies.sh).
