### ISSUE TITLE
extract_features file missing

### ISSUE THREAD

**Issue by nishant34** [AIBluefisher/deep_bundle_adjusting_NeRF#2]
I am getting the following error after commenting the disambiguation module dependency:

ImportError: cannot import name 'extract_features' from 'scripts' (/home/nishantjn/Dbarf/dbarf/scripts/__init__.py)

**Comment by AIBluefisher** [comment]
Sorry for the inconvenience, I'll fix the issue soon.

**Comment by whalien-902** [comment]
I have encountered the same issue as mentioned above. How can I solve it? Is the mentioned .py file currently missing from the open-source code? How can I obtain that file?

**Comment by hanyangyu1021** [comment]
The same problem

**Comment by AIBluefisher** [comment]
Hi, I'm too busy to fix the issue these weeks. For a temporary fixing, I'll provide a Google Drive link to the g2o files for my training data such that you can fine-tune the provided pre-trained model.

**Comment by samhodge-aiml** [comment]
Yeah this is still broken. Awaiting a fix to get past the first step into reproducing your paper with external data.

error message is as follows

```
  File "/media/sam/aimlwork/github/env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/sam/aimlwork/github/env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/sam/aimlwork/github/dbarf/scripts/preprocess_dbarf_dataset.py", line 6, in <module>
    from scripts import extract_relative_poses
  File "/media/sam/aimlwork/github/dbarf/scripts/extract_relative_poses.py", line 16, in <module>
    from scripts import extract_features, match_features, \
ImportError: cannot import name 'extract_features' from 'scripts' (/media/sam/aimlwork/github/dbarf/scripts/__init__.py)

```

**Comment by AIBluefisher** [comment]
It's fixed now. You can try to run the script again. Also check the [script](https://github.com/AIBluefisher/dbarf/blob/main/scripts/env/dependencies.sh) for dependencies.
